### ISSUE TITLE
Add support to endorsed certificate issuer: Entrust

### ISSUE THREAD

**Issue by cvarjao** [BCDevOps/certbot#1]
Entrust now supports ACME protocol. This ticket is for investigating the feasibility of using Entrust certificates.

Reference:
- https://www.entrustdatacard.com/knowledgebase/how-to-use-acme-to-install-ssl-tls-certificates-in-entrust-certificate-services-apache

**Comment by cvarjao** [comment]
E-mail have been sent to OCIO/IDMS team to start engagement and conversation.

**Comment by jujaga** [comment]
Support for custom `CERTBOT_SERVER` which allows for Entrust support added in e2f49525.
