### ISSUE TITLE
https://github.com/BCDevOps/certbot/blob/master/docker/Dockerfile#L23 is a little specific

### ISSUE THREAD

**Issue by bish0polis** [BCDevOps/certbot#10]
There's no need to target a specific mirror in https://github.com/BCDevOps/certbot/blob/master/docker/Dockerfile#L23, is there?  https://dl.fedoraproject.org/pub/epel/epel-release-latest-7.noarch.rpm may be a more reliable result.

**Comment by cvarjao** [comment]
I don't think so. I will include in the next change sets, or a PR is also welcome :D

**Comment by bish0polis** [comment]
> I don't think so

Your call.  Good luck!

**Comment by cvarjao** [comment]
Sorry, I wasn't very clear there. I think you are right. I don't think there is a need to target specific mirror.

**Comment by jujaga** [comment]
Addressed in [5883a93](https://github.com/jujaga/certbot/commit/5883a9311da55ddc0136d2d0c55b09927d896c91)
