### ISSUE TITLE
Multiple certbot-managed=true labels causes problem with uniq.

### ISSUE THREAD

**Issue by marklise** [BCDevOps/certbot#13]
`oc get route -l certbot-managed=true -o json | jq '.items[].spec.host' -r | sort -f | uniq -iu > /tmp/certbot-hosts.txt`

Here if you have multiple routes with different paths but the same domain causes the `uniq -iu` command to return nothing.  Tested on Openshift 4.x and Ubuntu 20.04 WSL.

Workaround: Label one route, run the certbot routine, and manually copy the certs into the other route yamls.

**Comment by jujaga** [comment]
Addressed in [6a0ac87](https://github.com/jujaga/certbot/commit/6a0ac870541a882b28deb286ba35650e334f3783)
