### ISSUE TITLE
Viewing "Example Service Desk Ticket"

### ISSUE THREAD

**Issue by rturgano** [BCDevOps/certbot#15]
Hello, I seem to not have permission to view the URL (https://apps.nrs.gov.bc.ca/int/jira/servicedesk/customer/portal/1/SD-26581). Is it possible to type it out on the page?

**Comment by jujaga** [comment]
Please contact whomever initiated that service desk request and see if they can add you to that ticket.
Closing this issue as this is issue is a question about internal process, not the code implementation itself.
