### ISSUE TITLE
Cerificate renewal stuck in 'pending'

### ISSUE THREAD

**Issue by TimCsaky** [BCDevOps/certbot#16]
We use certbot to request/renew a certifcate for `getok.nrs.gov.bc.ca`
We only use this non-www route but certbot makes requests for both www and non-www domains.
The non-www request was approved, but the www is declined by Entrust (with reason: 'Duplicate request with www. prefix. This is included in a standard license.')

However, the certbot seems to need both approved. Can anyone confirm if that is true?
The log on the certbot container looks like this:
```
Cert is due for renewal, auto-renewing...
Plugins selected: Authenticator standalone, Installer None
Renewing an existing certificate for getok.nrs.gov.bc.ca and www.getok.nrs.gov.bc.ca
Performing the following challenges:
http-01 challenge for www.getok.nrs.gov.bc.ca
Waiting for verification...
Cleaning up challenges
Attempting to renew cert (openshift-route-certs) from /etc/letsencrypt/renewal/openshift-route-certs.conf produced an unexpected error: All authorizations were not finalized by the CA.. Skipping.
All renewal attempts failed. The following certs could not be renewed:
  /etc/letsencrypt/live/openshift-route-certs/fullchain.pem (failure)

```

Any ideas much appreciated.
Not sure who maintains this repo these days... would be great to keep it alive.

**Comment by jujaga** [comment]
Addressed in [9eec62d](https://github.com/jujaga/certbot/commit/9eec62d3a1b763e575fa9e658dcaa61c33fcdf82)
