### ISSUE TITLE
No package certbot-1.3.0-1.el7 available

### ISSUE THREAD

**Issue by RajvirBains** [BCDevOps/certbot#5]
We have certbot deployment imbedded into our pipeline so we end up building the image quite often. Recently, our cert renewal pod reported the error `/usr/local/bin/oc-deploy-certs.sh: line 131: certbot: command not found` and after some investigation found that in the build process we have `No package certbot-1.3.0-1.el7 available` error. I will try updating the Certbot version and do a PR for this.

**Comment by RajvirBains** [comment]
talked to Clecio and inserting some logic to ensure that the code fails if a package is not found would be a good solution.

**Comment by cvarjao** [comment]
@RajvirBains , I believe this issue was resolved with PR 6, and it can be closed?

**Comment by RajvirBains** [comment]
correct, @cvarjao
