### ISSUE TITLE
grouping requests certs

### ISSUE THREAD

**Issue by cvarjao** [BCDevOps/certbot#7]
right now, all routes gets lumped into 1 certificate request. We may need a way of splitting into multiple requests

**Comment by BcGovNeal** [comment]
@cvarjao I recently ran into this issue where I need to renew domains with different expiry dates.  I ended up modifying the script to use an additional label (`application`) on the routes.  I'm also creating a separate cronjob and PVC for each set of domains I need to renew separately.  I don't think this is the best solution but I needed work around quickly.

https://github.com/BcGovNeal/certbot/commit/198f18f1d058b77eb989eb636e95319c666c1cd6

**Comment by jujaga** [comment]
Addressed in a different way on #28
